### PR TITLE
Add description field to option block object

### PR DESCRIPTION
**Pull request by deto-r**
This PR,
Same content as PR [#766 ](https://github.com/slack-go/slack/pull/766).
Verification please.

### CODE REVIEW

**Comment by deto-r** [comment]
With this change, the argument of NewOptionBlockObject function is increased by one.

**Review by kanata2 — APPROVED** [review]
Looks good to me.
I think we should release this changes in next minor version(v0.7.0).

**Comment by jeremiepiotte-districtm** [comment]
Hey guys, I'd like to +1 this feature.

Can we merge this PR or are we waiting on something?

**Comment by deto-r** [comment]
I think I'm waiting for another review of status.

@kanata2 
What's the status now?

**Comment by kanata2** [comment]
Sorry for the delay. We are planning to release now. Could you please wait a little longer?

**Comment by kanata2** [comment]
released!

**Pull request merged**
