### PR TITLE
Fix support for CheckboxGroups (PR #685)

### PR DESCRIPTION
**Pull request by ghost**
Hello,

I was just playing around with CheckboxGroups and the PR proposed by @eliot-stripe in #685 (I saw it was just merged - I was a bit too late ;). I noticed that he missed several places where CheckboxGroups are (Un)Marshalled in the structs if you use them in Modals etc.

I could successfully create & modify CheckboxGroups with the additional changes in this PR.

Thanks!

### CODE REVIEW

**Review by kanata2 — APPROVED** [review]
Looks good to me :)

**Review by ollieparsley — APPROVED** [review]
Thank you @ttgmpsn for spotting it and fixing the issue :)

**Comment by eliot-stripe** [comment]
Thanks for catching my mistake @ttgmpsn

**Comment by ghost** [comment]
Hey! Is something preventing this PR from being merged? I need to deploy some software that uses this (and, as part of an automated deploy process, tries to fetch the latest version from github). Thanks :)

**Comment by ollieparsley** [comment]
It is now merged. Apologies for the delay.

**Pull request merged**
