### PR TITLE
added method tooling.tokens.rotate

### PR DESCRIPTION
**Pull request by dhalturin**
Added sending a request for the method:
https://api.slack.com/methods/tooling.tokens.rotate

`Exchanging a refresh token for a new app configuration token.`

### CODE REVIEW

**Comment by dhalturin** [comment]
@kanata2, hello! could you please check this PR?

**Review by parsley42 — APPROVED** [review]
Doesn't appear to be harmful/breaking.

**Comment by parsley42** [comment]
Ah, I see this introduced a conflict with another merged PR - automated testing FTW I guess. Feel free to rework this to gel with the current tree.

**Comment by dhalturin** [comment]
@parsley42, branch has been synced with master

**Comment by dhalturin** [comment]
lol, the method was added while the PR was open for half a year

**Comment by parsley42** [comment]
@dhalturin Hah - yeah, I'm really just filling in as maintainer until somebody better steps up. I figure the work I'm doing is better than no merges at all. In any case, it looks like the tests are still failing?:
```
panic: http: multiple registrations for /tooling.tokens.rotate [recovered]
	panic: http: multiple registrations for /tooling.tokens.rotate
```

**Comment by dhalturin** [comment]
@parsley42, I think it doesn't matter now _)

**Pull request closed without merging**
