### PR TITLE
Add context support

### PR DESCRIPTION
**Pull request by dlsniper**
### This will be merged on May 31, 2017

RTM (websockets) support is not yet present, to be determined how to be best implemented.

### CODE REVIEW

**Comment by dlsniper** [comment]
Uhm, turns out this breaks the Go < 1.7 support. People should be at least on 1.7, right?

**Comment by dlsniper** [comment]
Well, I've made a [new release](https://github.com/nlopes/slack/releases/tag/v0.1.0) to get around this problem.

**Comment by dlsniper** [comment]
This will be merged on May 31, 2017

**Comment by joefitzgerald** [comment]
@dlsniper May 31 has come and gone, would you mind merging? This is a great improvement to the package.

**Comment by dlsniper** [comment]
Hi @joefitzgerald, I must apologize for the delay, something came up and I also took the opportunity to have it tested a bit more via [gopher](https://github.com/gopheracademy/gopher) before I release such a big change to the world.

**Pull request merged**
