### PR TITLE
Refactor with some tools

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
These tools are used with [gometalinter](https://github.com/alecthomas/gometalinter).
Notice that gofmt fixes codes automatically but other tools alert but don't fix codes.
I have fixed codes manually according to alerts.

* gofmt
* go vet
* [gosimple](https://github.com/dominikh/go-tools/tree/master/cmd/gosimple)
* [misspel](https://github.com/client9/misspell)
* [nakedret](https://github.com/alexkohler/nakedret)
* [unconvert](https://github.com/mdempsky/unconvert)

### CODE REVIEW

**Comment by dvdplm** [comment]
This looks like all valid and welcome cleanup to me. LGTM.

**Comment by suzuki-shunsuke** [comment]
@dvdplm 
Thank you for your review.

@james-lawrence 
Thank you for your review.
I always appreciate your review, but I have a request.
Please don't squash merge.
It is difficult to revert a specific change in a pull request if it is squash merged.
Squash merging spoils my effort to make commits clean.
If you want to merge some commits to other commits, please let me fix before squash merging.
I don't request any more about this pull request because it is difficult to fix.

**Comment by james-lawrence** [comment]
@suzuki-shunsuke sure thing, TBH I squash merge for the same reason you don't want me to. easier to revert a single commit than go through and figure out which individual one causes it.

Many people don't put effort into the individual commits, as a result you'll get commits that can't be reverted cleanly etc. So its easier on my end to just squash.

**Comment by suzuki-shunsuke** [comment]
@james-lawrence 
Thank you for your reply.
I see.

**Pull request merged**
