### PR TITLE
Add support for Rich Text Input

### LINKED ISSUE #1239: Support rich text input
### Description

Support [rich text input](https://app.slack.com/block-kit-builder/T06FNKK2N#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22rich_text_input%22,%22action_id%22:%22rich_text_input-action%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%22,%22emoji%22:true%7D%7D%5D%7D) 

```
	"blocks": [
		{
			"type": "input",
			"element": {
				"type": "rich_text_input",
				"action_id": "rich_text_input-action"
			},
			"label": {
				"type": "plain_text",
				"text": "Label",
				"emoji": true
			}
		}
	]
```

### (Optional) Slack's documentation
[rich text input](https://api.slack.com/reference/block-kit/block-elements#rich_text_input)

### PR DESCRIPTION
**Pull request by peimanja**
closes #1239

### CODE REVIEW

**Comment by floydjones1** [comment]
@kanata2 @parsley42 could we get someone to take a look at this please? 🤞 
I can help if there is anything I can do to speed this up

**Comment by parsley42** [comment]
Hi @floydjones1 - I haven't heard from @kanata2 in some time; he did a great job maintaining for a while, but most likely he's busy with other things now. I do occasional reviews and merges, but I'm more a DevOps engineer than Go dev - honestly, I'm kind of a lousy Go dev, but I've been getting new maintainers on board for a few years now. Unfortunately volunteer maintainers have really dried up - we get a few PRs, but so far nobody has taken on the role. If you or somebody you know is an experienced Go dev and would like to volunteer as a maintainer, I'd be happy to onboard somebody new.

**Review by pakistancan — APPROVED** [review]

**Review by parsley42 — APPROVED** [review]
Looks harmless.

**Comment by chase-allen-tech** [comment]
Seems like this integration needs additional API modification to read rich text in the request.
Here [blockkit](https://app.slack.com/block-kit-builder/THNMV7RT9#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22rich_text_input%22,%22action_id%22:%22rich_text_input-action%22,%22initial_value%22:%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22I%20have%20two%20meetings%22%7D%5D%7D%5D%7D,%22placeholder%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Enter%20text%22%7D%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22,%22initial_value%22:%22test%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%22,%22emoji%22:true%7D%7D,%7B%22type%22:%22section%22,%22fields%22:%5B%7B%22type%22:%22plain_text%22,%22text%22:%22*this%20is%20plain_text%20text*%22,%22emoji%22:true%7D%5D%7D,%7B%22type%22:%22rich_text%22,%22elements%22:%5B%7B%22type%22:%22rich_text_section%22,%22elements%22:%5B%7B%22type%22:%22text%22,%22text%22:%22Hello%20there,%20%22%7D,%7B%22type%22:%22text%22,%22text%22:%22I%20am%20a%20bold%20rich%20text%20block!%22,%22style%22:%7B%22bold%22:true%7D%7D%5D%7D%5D%7D%5D%7D) shows `Text` to be slice of object, but [TextBlockObject](https://github.com/slack-go/slack/blob/af783b3055b15b0ea99c0e956716e1d7d94e76c2/block_object.go#L122) only require string.
I can't get request value of the rick text. 
[peimanja](https://github.com/peimanja) could you have a look?
CC: [parsley42](https://github.com/parsley42)

**Pull request merged**
