### PR TITLE
Update Gopkg.lock with dep v0.5.0

### PR DESCRIPTION
**Pull request by kei-yamazaki**
New fields pruneopts and deigest were added at dep v0.5.0.

see: https://golang.github.io/dep/blog/2018/07/25/announce-v0.5.0.html

### CODE REVIEW

**Comment by kei-yamazaki** [comment]
@james-lawrence I can't understand what does [this comment](https://github.com/nlopes/slack/pull/404#issuecomment-424006939) mean.

Please tell me the case that dep can not prune properly.

**Comment by james-lawrence** [comment]
https://github.com/golang/dep/issues/1847, doesn't directly apply to this package. but I don't feel like diagnosis issues it may cause for other corner cases.

**Comment by james-lawrence** [comment]
mind just rebasing your branches against master? I fat fingered a push =/

**Comment by kei-yamazaki** [comment]
@james-lawrence Thanks for the information.
I agree your thought too, so I disabled the prune option.

Some vendor files are added in this commit because I executed `dep ensure` command with disabling pruning.

**Comment by kei-yamazaki** [comment]
Some vendor's tests can't pass the travis...

**Comment by james-lawrence** [comment]
sorry, should have clarified.

pruning tests is okay.
pruning unused dependencies isn't. =)

[prune]
  go-tests = true

**Pull request closed without merging**
