### PR TITLE
Goodbye vendor dir

### PR DESCRIPTION
**Pull request by kanata2**
Remove vendor directory

### CODE REVIEW

**Comment by obalunenko** [comment]
Prefer to keep venor directory committed to have reproducible builds and be save from disappearing of libraries from GitHub.
https://blog.boot.dev/golang/should-you-commit-the-vendor-folder-in-go/

**Review by obalunenko — CHANGES_REQUESTED** [review]
Prefer to keep vednor directory committed to have reproducible builds and be save from disappearing of libraries from GitHub.
https://blog.boot.dev/golang/should-you-commit-the-vendor-folder-in-go/

**Comment by kanata2** [comment]
My understanding is that Go modules should remain cached in the module proxy even if a repository is deleted.

**Comment by obalunenko** [comment]
@kanata2 Unfortunately proxy servers that're not self hosted cannot provide any guarantee that they will not lose module.
Anyway this topic was always controversial. Just interesting article to read https://www.ardanlabs.com/blog/2020/04/modules-06-vendoring.html

**Review by zchee — APPROVED** [review]
I think self hosted proxy server haven't good SLO than hosted by Google Go team. so LGTM.

**Pull request merged**
