### PR TITLE
[Feat] conversations.mark

### PR DESCRIPTION
**Pull request by ramikalai**
Slack has added a conversations.mark endpoint which will replace the existing im, mpim, channel and group mark endpoints.

This PR implements the new endpoint.

### CODE REVIEW

**Comment by ramikalai** [comment]
This solves issue #749

**Comment by ramikalai** [comment]
@ollieparsley can you please check and merge?

**Review by ollieparsley — CHANGES_REQUESTED** [review]
Hey @ramikalai thank for you this and apologies for the delay! Could you add a test into `converstation_test.go` please. Once you've done that I'll get it merged.

**Comment by KarimNahas** [comment]
@ollieparsley is it fine to merge now? (not really sure what are the standards / expectations for your test suite)

**Review by kanata2 — APPROVED** [review]
Thanks.

**Pull request merged**
