### PR TITLE
refactor PostMessage/UpdateMessage, add SendMessage.

### PR DESCRIPTION
**Pull request by james-lawrence**
- allows providing attachments when updating a message. (via SendMessage)
- makes the usage for sending a message more general.

Fixes #145, #146

### CODE REVIEW

**Comment by james-lawrence** [comment]
@nlopes I'd like to get this work merged or something similar so I can make further changes. I have some fixes to disconnect I'd like to work on to allow safe shutdowns of the RTM. any chance of this being merged if I fix the conflict?

**Comment by james-lawrence** [comment]
I'll also likely have slack grid work coming up. this also resolved #145, and #146

**Comment by dlsniper** [comment]
Hi @james-lawrence,

Since this is a bit of a change, I'll try and review it asap and get you some feedback / merged.
Probably I'll do so this weekend.
Thank you for your patience.

**Comment by dlsniper** [comment]
LGTM, sorry for the delay.

**Pull request merged**
