### PR TITLE
Adding Support for Dialogs

### PR DESCRIPTION
**Pull request by edwardIshaq**
Hi there,
I was working on this until I found out that there is already a PR open https://github.com/nlopes/slack/pull/319 

I was wondering if you think I should close this and wait for the earlier PR to merge ? 

Thanks.

### CODE REVIEW

**Comment by edwardIshaq** [comment]
Hi @james-lawrence 
Any chance you could take a look at this fork please ?
A few differentiators from the PR referenced above:
- `dialogSelect.go` explicitly breaks down the select builder into an easy constructors and strict types of dataSources.
- `dialogSelect.go` also provides easy methods to include preset pickers such as user/channel/conversations.
- `dialogText.go` provides explicit subtypes and easy constructors to use
- tests are included...

**Comment by james-lawrence** [comment]
yes will take a closer look this weekend. I only spend an hour or so if possible during the weekends to manage this stuff. =p

**Comment by sashker** [comment]
Hello, @edwardIshaq 

I applied your patch and encountered an error:
there is no a sructure ResponseMetadata

// DialogOpenResponse response from `dialog.open`
type DialogOpenResponse struct {
	Ok                     bool             `json:"ok"`
	Error                  string           `json:"error"`
	DialogResponseMetadata ResponseMetadata `json:"response_metadata"`
}

// DialogResponseMetadata lists the error messages
type DialogResponseMetadata struct {
	Messages []string `json:"messages"`
}

**Comment by edwardIshaq** [comment]
Good catch @sashker and thank you for finding that bug.
I've pushed a fix, let me know if you see anything else.

it should've been:
```
type DialogOpenResponse struct {
	Ok                     bool             `json:"ok"`
	Error                  string           `json:"error"`
	DialogResponseMetadata ResponseMetadata `json:"response_metadata"`
}
```
as per the docs https://api.slack.com/methods/dialog.open

**Comment by edwardIshaq** [comment]
@sashker, did you get a chance to try out the updated version ?

**Comment by sashker** [comment]
@edwardIshaq I've tried it. After receiving a /slash command I successfully create a new dialog and show a simple form. Unfortunately can't test all functions at the moment.

I mentioned that if a slack token is wrong then OpenDialog function allegedly works (error=nil), but in fact, the request is unauthorized and the dialog doesn't occur. E.g. api.PostMessage shows **invalid_auth** in that case.

**Comment by edwardIshaq** [comment]
@sashker Thank you for the feedback, I will make sure that returns an error back in that case. I will add more test cases to make it easy to run through the examples and try out different features

**Comment by james-lawrence** [comment]
this branch could use a rebase and reintegration with master. had some other dialog changes get merged.

**Comment by james-lawrence** [comment]
closing out in favor of #393

**Pull request closed without merging**
