### PR TITLE
Add id field to attachments

### PR DESCRIPTION
**Pull request by sazarkin**
Add id field to attachment.

Example from here here https://api.slack.com/docs/interactive-message-field-guide

```javascript
{
        "actions": [
            {
                "name": "channels_list",
                "selected_options": [
                    {
                    "value": "C012AB3CD"
                    }
                ]
            }
        ],
        "callback_id": "select_simple_1234",
        "team": {
            "id": "T012AB0A1",
            "domain": "pocket-calculator"
        },
        "channel": {
            "id": "C012AB3CD",
            "name": "general"
        },
        "user": {
            "id": "U012A1BCD",
            "name": "musik"
        },
        "action_ts": "1481579588.685999",
        "message_ts": "1481579582.000003",
        "attachment_id": "1",
        "token": "iUeRJkkRC9RMMvSRTd8gdq2m",
        "original_message": {
                "text": "It's time to nominate the channel of the week",
                "bot_id": "B08BCU62D",
                "attachments": [
                    {
                       "callback_id": "select_simple_1234",
                       "fallback": "Upgrade your Slack client to use messages like these.",
                       "id": 1,
                       "color": "3AA3E3",
                       "actions": [
                           {
                               "id": "1",
                               "name": "channels_list",
                               "text": "Which channel changed your life this week?",
                               "type": "select",
                               "data_source": "channels"
                           }
                        ]
                    }
                ],
                "type": "message",
                "subtype": "bot_message",
                "ts": "1481579582.000003"
        },
        "response_url": "https://hooks.slack.com/actions/T012AB0A1/123456789/JpmK0yzoZDeRiqfeduTBYXWQ"
}
```

### CODE REVIEW

**Comment by dvdplm** [comment]
@sazarkin While the `id` field does appear in the example you link to, there's no mention of it in the Attachment [docs](https://api.slack.com/docs/message-attachments) so that makes me a little worried. Do you know what the purpose of the `id` field is and perhaps what the use case might be?

**Comment by sazarkin** [comment]
Well, I am thinking that "attachment_id" is pointing on this field.
I am using it to understand, which attachment performed action.

**Comment by dvdplm** [comment]
@sazarkin Would you mind pinging Slack support and ask them about this field? With contradicting/unclear docs I'm hesitant to add more fields.

**Comment by dvdplm** [comment]
@sazarkin any update on this?

**Comment by sazarkin** [comment]
From slack support team:
screenshot from 2018-01-24 14-20-43

**Comment by james-lawrence** [comment]
LGTM.

**Pull request merged**
