### PR TITLE
Rename message json field inside MessageAction

### PR DESCRIPTION
**Pull request by jameslafa**
Here is a simple pull request to fix the issue #378.

### CODE REVIEW

**Comment by james-lawrence** [comment]
thanks btw.

**Comment by cjsaylor** [comment]
@james-lawrence I think there may be a problem with this. While this may fix in one area, it looks like interactive messages flow through this `MessageAction` as well, and it has "original_message" as the key in order to allow replacing the message with out the actions in it.

See https://api.slack.com/interactive-messages

So this change breaks interactive messaging (my use case).

**Comment by james-lawrence** [comment]
well shit... I'll push a change tonight. we'll just put both fields.

**Comment by jameslafa** [comment]
Yes I was not very confident pushing this without tests actually, I was lacking a bit of time. 
I think we should add that as soon as we can to make sure it does not happen again.

**Comment by james-lawrence** [comment]
problem is I'm not terribly familiar with the events API and slack occasionally makes changes to the structure of their api.

so minor changes like this which seem reasonable given relevant documentation can get overlooked.

**Comment by berfarah** [comment]
Question (from a completely uninformed standpoint here): why are there two types for this?

In `slackevents`:
https://github.com/nlopes/slack/blob/752f784a75e8b640f048a8a453466cca64c83a47/slackevents/action_events.go#L20-L35

and in `slack`:
https://github.com/nlopes/slack/blob/752f784a75e8b640f048a8a453466cca64c83a47/attachments.go#L44-L63

Which of these is the maintained and/or preferred way to interact with actions?

**Comment by james-lawrence** [comment]
MessageAction is for the events API.
slack/attachments is for the interactions API. and is being refactored into an interactions structure.

your use should depend on which slack API you're using. they exist because no one has ensured they truly are identical and be used interchangeably and that it will remain that way.

**Comment by berfarah** [comment]
@james-lawrence Thanks for taking the time to respond. Sounds good! I'm only using the interactive API, so I think for now I'll use the former. One thing to note: there's a very minor difference between the two structs where `ID` and `URL` are capitalized in `slack/attachments.go` and not in `slackevents`.

**Comment by james-lawrence** [comment]
feel free to submit a fix for slackevents.

**Comment by berfarah** [comment]
@james-lawrence cheers, done! Thanks for maintaining!

**Pull request merged**
