### PR TITLE
Allow message unfurling with auth URL

### PR DESCRIPTION
**Pull request by zerok**
This PR is basically a continuation of prior work by @kautsig in #839. I've just extracted his change into a separate branch for easier merging and added some test cases.

## API changes

- Adds UnfurlMessageWithAuthURL method to the client
- Adds UnfurlMessageWithAuthURLContext method to the client
- Adds MsgOptionUnfurlAuthURL used within the two methods above

The Unfurl methods were added to be consistent with the UnfurlMessage method already exposed by the client.

### CODE REVIEW

**Comment by ds0nt** [comment]
Should also add these so I can authenticate users in unfurling flows as described here:

flow:

https://api.slack.com/reference/messaging/link-unfurling#authenticated_unfurls

things still to add:

https://api.slack.com/methods/chat.unfurl#arg_user_auth_required
https://api.slack.com/methods/chat.unfurl#arg_user_auth_message

**Comment by ds0nt** [comment]
"Specifying `user_auth_url` or user_auth_message will automatically imply `user_auth_required` being set to true. If both `user_auth_url` and `user_auth_message` are provided, `user_auth_message` takes precedence."

**Comment by zerok** [comment]
@ds0nt Good point. I'll add them on Monday to the PR 🙂

**Comment by zerok** [comment]
@ds0nt done :)

**Review by kanata2 — APPROVED** [review]
LGTM! Thank you.

**Comment by ds0nt** [comment]
Thanks! :D!

**Pull request merged**
