### PR TITLE
Message Struct Lacking ClientMsgID

### PR DESCRIPTION
**Pull request by ramikalai**
Added an ID field (string - no omitempty) to distinguish between different messages coming from the server.

### CODE REVIEW

**Comment by ramikalai** [comment]
@ollieparsley can't seem to request review on this...

**Comment by ollieparsley** [comment]
@ramikalai no worries. Did you run the tests for this? I know some of the tests and structs depend on the order of the structs properties, just want to make sure this isn't affected. If it passed, I'll merge :). 

You can run `make pr-prep` to run all linting and tests

**Comment by ramikalai** [comment]
@ollieparsley running now

**Comment by ramikalai** [comment]
image
@ollieparsley Done!

**Comment by ollieparsley** [comment]
@ramikalai thanks!

**Pull request merged**
