### PR TITLE
fix: Updated RichTextInputBlockElement InitialValue data type

### PR DESCRIPTION
**Pull request by Manjish**
##### Pull Request Guidelines

These are recommendations for pull requests.
They are strictly guidelines to help manage expectations.

##### PR preparation
Run `make pr-prep` from the root of the repository to run formatting, linting and tests.

##### Should this be an issue instead
- [x] is it a convenience method? (no new functionality, streamlines some use case)
- [ ] exposes a previously private type, const, method, etc.
- [ ] is it application specific (caching, retry logic, rate limiting, etc)
- [ ] is it performance related.

Fix for [issue #1276](https://github.com/slack-go/slack/issues/1276)
Updated the datatype of RichTextInputBlockElement InitialValue from string to *RichTextBlock

### CODE REVIEW

**Review by lorenzoaiello — CHANGES_REQUESTED** [review]
@Manjish , thank you for the contribution!

It looks like there are some files that were perhaps mistakenly committed that change a lot of the imports to the forked github paths. Can you please fix those?

**Comment by Manjish** [comment]
@lorenzoaiello 
Thanks for pointing it out. I changed to test in my local.
I have reverted the changes. 
Thank you 🙇

**Comment by Manjish** [comment]
> @Manjish , thank you for the contribution!
> 
> It looks like there are some files that were perhaps mistakenly committed that change a lot of the imports to the forked github paths. Can you please fix those?

@lorenzoaiello 
Thanks for pointing it out. I changed to test in my local.
I have reverted the changes.
Thank you 🙇

**Review by lorenzoaiello — APPROVED** [review]
Thanks for a quick follow up!

**Pull request merged**
