### PR TITLE
Export conversations for testing

### LINKED ISSUE #497: Cannot mock slack.Channel
## Expected Behavior

Being able to create a new mock channel for testing

## Actual Behavior

Because `groupConversation` is not exported, I can't set the channel name.

## Repro Steps

```Go
testSlackChannel := &slack.Channel{
	Name: "foo",
}
```

```
cannot use promoted field groupConversation.Name in struct literal of type ".../vendor/github.com/nlopes/slack".Channel
```

This was also called out in #78

### PR DESCRIPTION
**Pull request by ghostsquad**
This allows a couple resources like channels to be mocked,
as it exports the embedded structs

Resolves #497

### CODE REVIEW

**Comment by ghostsquad** [comment]
Note: gopkg.Lock was updated after I ran `dep ensure`. Possibly because I'm running a newer version?

**Comment by james-lawrence** [comment]
requires a rebase due to conflicts.

**Comment by wesmcnamee-avalara** [comment]
@james-lawrence rebase complete.

**Comment by ghostsquad** [comment]
@james-lawrence rebase complete

**Comment by james-lawrence** [comment]
remove the Gopkg.lock, you didn't touch the depency tree. and its conflicting unnecessarily.

**Comment by ghost** [comment]
@james-lawrence done

**Comment by ghostsquad** [comment]
@james-lawrence any chance this can be merged?

**Pull request merged**
