### PR TITLE
[experimental] introduction of Slack workflow steps

### PR DESCRIPTION
**Pull request by SteffenMahler**
New experimental feature "Slack workflow steps" added

- [x] `make pr-prep`
- [x] tests included
- [x] dependency github.com/google/go-cmp/cmp for test added
- [x] example App included

### CODE REVIEW

**Comment by kanata2** [comment]
Thanks! I'll confirm later 👀 

BTW, please use `workflow_step` instead of `workflowStep` in dir name and file name.

**Comment by kanata2** [comment]
@SteffenMahler 
Could you confirm this?
https://github.com/slack-go/slack/runs/5167540820

**Comment by SteffenMahler** [comment]
@kanata2 
Yes, I will check the linter problem soon and let you know when I am done.

**Comment by SteffenMahler** [comment]
Hello @kanata2 

I have switched to goimports for sorting and formatting of imports. So the linter check should be successful now.
Maybe we should integrate `docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.44.0 golangci-lint run -v` into the makefile?
Could you be so kind as to start the action again?

Thank you.

**Comment by zchee** [comment]
@SteffenMahler Hi, this is newer slack-go maintainer.

The `webhooks_go112.go` and `webhooks_go113.go` files has been removed (my previous pull request). Could you rebase it?

---

As you suggested:

> Maybe we should integrate docker run --rm -v $(pwd):/app -w /app golangci/golangci-lint:v1.44.0 golangci-lint run -v into the makefile?

Yeah, our GitHub Actions policy's don't running until accepted by any maintainers (I hope it's a commonly used policy). So contributor can't checks whether the will fail lint job or etc.
Make sense, I'll consider adding it. Thanks.

**Comment by SteffenMahler** [comment]
Hi @zchee,

I don't know what I did wrong. Now there are changes in my branch that I didn't made and should already be in the main branch. Can you have a look?

**Comment by zchee** [comment]
@SteffenMahler Sure, will review soon.

**Comment by viktor42b** [comment]
FYI, we are currently using your branch in our internal project. This is working perfectly & deployed into production. Really much needed.

**Comment by zchee** [comment]
@victorboissiere Thanks for great feedback. We should merge ASAP anyway.

**Review by zchee — APPROVED** [review]
LGTM

**Pull request merged**
