### PR TITLE
add `channels` optional argument to usergroups.update

### PR DESCRIPTION
**Pull request by an-stripe**
[usergroups.update](https://api.slack.com/methods/usergroups.update) allows an optional argument, `channels`, for setting the list of default channels for the User Group. We should send this argument if it's provided.

### CODE REVIEW

**Comment by james-lawrence** [comment]
LGTM, mind just rebasing off master and I'll merge.

**Comment by an-stripe** [comment]
Thanks @james-lawrence - I rebased!

**Comment by james-lawrence** [comment]
hm wonder why its not applying cleanly?

**Comment by asf-stripe** [comment]
Hi there, I've been taking on work that depends on this change & wonder if you can try merging again? If there are any problems with the patch, I can take a stab at getting it to apply cleanly.

**Comment by an-stripe** [comment]
@asf-stripe - I don't have merge permissions. I'm not sure how to help trouble shoot at this point but maybe @james-lawrence can take another shot.

**Comment by asf-stripe** [comment]
Hah, yep, sorry @an-stripe - I meant to address @james-lawrence with that message, since he has the merge permissions after all ((:

**Comment by asf-stripe** [comment]
Looks like this made it into the code base in c33a46b52751322265b0e3f6243aaa462c738684 after all! \o/!!

**Pull request closed without merging**
