### PR TITLE
Add support for "Client token"/Cookie auth

### PR DESCRIPTION
**Pull request by rusq**
Encouraged by @nolanlum in #996, opening a PR, hoping that this would be useful to community.

##### PR preparation
- [x] Run `make pr-prep` from the root of the repository to run formatting, linting and tests.

##### What has changed
This PR adds support for slack client token/cookie (xoxc, xoxd) pair authentication by adding two options that may be passed on instantiation of the Client:

- `OptionCookie(name,value)` - convenience function that allows  adding a "slack.com" cookie that will be added to each request.
- `OptionCookieRAW(cookies ...*http.Cookie)` - gives more flexibility and allows adding any custom cookie.  Main intent of this function is to allow the caller to pass the cookies from Mozilla "cookies.txt".

This change affects `downloadFile`, and `postForm` functions and the calling function.  All others remain untouched (i.e. `doPost` and its callers).  Reason for that - the application that uses this function ([slackdump](https://github.com/rusq/slackdump))  is read-only, and I simply wouldn't be able to test that in practical application, but would be open if someone stands up to help me updating those, if required.

Either way - it might be a good starting point to add the support for this.

### CODE REVIEW

**Comment by rusq** [comment]
The Go 1.17 failure does not seem related to the change?

**Comment by rusq** [comment]
Hey @nolanlum is there a reason that this hasn't been given attention yet?

Is there anything needing to be addressed?

**Comment by nolanlum** [comment]
> Hey @nolanlum is there a reason that this hasn't been given attention yet?

I don't actually have write access! So my review wouldn't mean very much. But it does look good to me.

**Review by nolanlum — APPROVED** [review]

**Comment by rusq** [comment]
> > Hey @nolanlum is there a reason that this hasn't been given attention yet?
> 
> 
> 
> I don't actually have write access! So my review wouldn't mean very much. But it does look good to me.

Thank you anyway :) now it is not so lonely in this PR!

**Comment by robrecord** [comment]
I an unable to authenticate with any other method for some reason - would be great to see this PR reviewed by someone with write access :-)

**Comment by rusq** [comment]
Happy New Year!

**Comment by rusq** [comment]
Whoever's going to be searching for this, the solution is already there, no need to build anything custom:
- I was able to work around that by using a custom `http.Client` with a cookie jar and passing `OptionHTTPClient` to slack.New. [Example](https://github.com/rusq/slackdump/blob/85358171b3fd3c44e78f82e4dbd684d84eb4be74/slackdump.go#L116)

You can grab the chttp implementation from slackdump or BYO.

Thanks, you're welcome. Closing this.

**Pull request closed without merging**
