### PR TITLE
slack/team: GetTeamInfo for Slack Client is added

### PR DESCRIPTION
**Pull request by mehmetalisavas**
hey @nlopes 
I've searched for TeamInfo method for slack but i couldn't find.
Then I've used this and this may be helpful for others also..

By the way, good work.. !!

### CODE REVIEW

**Comment by nlopes** [comment]
Do you mind adding tests? I know they are currently lacking in a lot of these calls but I am thinking it is about time we all start adding them (that goes for me as well). 
Thanks for this!

**Comment by mehmetalisavas** [comment]
I've added a simple test for it with incoming data. 
Also parsing is working as well ..

**Comment by nlopes** [comment]
Will merge once those commits are squashed ;)

**Comment by mehmetalisavas** [comment]
@nlopes thx for ur attention :)

**Pull request merged**
