### PR TITLE
Implement reactions

### PR DESCRIPTION
**Pull request by rcarver**
This branch adds support for the [Reactions API](https://api.slack.com/methods/reactions.add)
- [x] Implement `reactions.add`
- [x] Implement `reactions.get`
- [x] Implement `reactions.list`
- [x] Implement `reactions.remove`
- [x] Add tests
- [x] Add example file

### CODE REVIEW

**Comment by nlopes** [comment]
:+1:

**Comment by rcarver** [comment]
@nlopes How does this look to you? The polymorphic stuff is tricky, but maybe we can share an approach between reactions and stars.

**Comment by nlopes** [comment]
Overall looks good. Let me give it another pass this weekend and I'll merge assuming nothing pressing comes up. 
Thanks!

**Comment by rcarver** [comment]
Ok, really done now. Also check #33 to see how the approach extends to improve stars.

**Pull request merged**
