### PR TITLE
Update AuthTestResponse to include bot_id

### PR DESCRIPTION
**Pull request by amossc**
##### Pull Request Guidelines

This is a fix for #777 

Executed `make pr-prep`

### CODE REVIEW

**Comment by kanata2** [comment]
Thanks!
The `enterprise_id` is included if you use Slack Enterprise Grid.
So please leave this field 🙏

**Comment by kanata2** [comment]
@amossc any update?

**Comment by amossc** [comment]
> Thanks!
> The `enterprise_id` is included if you use Slack Enterprise Grid.
> So please leave this field 🙏

Sorry. I added it back and rebased on current master. Will squash when I merge.

**Review by kanata2 — APPROVED** [review]
Thank you!

**Pull request merged**
