### PR TITLE
Implement method UpdateMessageWithAttachments

### PR DESCRIPTION
**Pull request by mkungla**
Added UpdateMessageParameters which  contains all the parameters necessary (including the optional ones) for a UpdateMessageWithAttachments() request which updates a message in a channel with attachments. I added new method so that it would not become breaking change for others.

### CODE REVIEW

**Comment by james-lawrence** [comment]
see https://github.com/nlopes/slack/pull/121

**Comment by mkungla** [comment]
@james-lawrence yours will introduce braking changes right? Anyhow seems that @nlopes is not up to maintain this repository or does not have enough time for it which forces me to develop further under my fork or re design that API Client from scratch since I find that API client should be more consistent with the endpoints scema instead of inventing new method names and parameter stucts which do not match with endpoint. Here are some example What I mean:

| actual endpoint | method here | better would be |
| --- | --- | --- |
| `bots.info` | `GetBotInfo` | `BotsInfo` |
| `channels.archive` | `ArchiveChannel` | `ChannelsArchive | Channels.Archive` |
| `channels.unarchive` | `UnarchiveChannel` | `ChannelsUnarchive | Channels.Unarchive` |
| dnd.endDnd | EndDND | `DndEndDnd | Dnd.EndDnd` |

and so on.

**Comment by james-lawrence** [comment]
mine shouldn't introduce any api changes, if I did they were unintentional. I added a new method that the old ones delegate down to.

I'm in general not opposed to breaking changes if it forwards a library, as long as the library is versioned. In my own libraries I would have changed the signature of PostMessage instead of adding the new method.

As for the naming, I'm fairly indifferent long as they are clear. My issues main issues revolve around
- RTM not having a safe shutdown/startup sequence.
- the http client being completely inaccessible. (it should be something that can be configured and passed in.
- private member structs requiring setting by struct.field = instead of struct{field:}

**Comment by dlsniper** [comment]
I'll have a review of this and #121 soon (hopefully by the end of the weekend).
As far as I can see #121 doesn't introduce any API changes but it's a pretty decent sized one and I'd rather be safe than sorry.

**Comment by dlsniper** [comment]
Fixed in #121, sorry for the delay.

**Pull request closed without merging**
