### PR TITLE
Fix bug in merge #8 from wrong conversion of bool to string

### PR DESCRIPTION
**Pull request by Wiwiweb**
Actually I messed up, converting a bool to string is not as simple as `string(bool)`. Terribly sorry about that :(

I ended up just copying the way you did it for `UnfurlLinks` and `UnfurlMedia` which is to just hardcode write the opposite bool value of the default.

### CODE REVIEW

**Comment by mediocregopher** [comment]
+1

**Comment by kentaro** [comment]
:+1:

**Comment by dojineko** [comment]
:+1:

**Comment by yuya-takeyama** [comment]
:+1:

**Comment by kyokomi** [comment]
:+1:

**Comment by bfontaine** [comment]
It’d be great to have this merged, since the bug breaks the build and thus prevents people from installing the library:

```
$ go get github.com/nlopes/slack
# github.com/nlopes/slack
../../nlopes/slack/chat.go:135: cannot convert params.AsUser (type bool) to type string
```

**Comment by nlopes** [comment]
Glorious vacations without cell reception :)
/merged

**Pull request merged**
