### PR TITLE
file.upload: allow uploads with io.Reader

### PR DESCRIPTION
**Pull request by dennwc**
This change is [Reviewable](https://reviewable.io/reviews/nlopes/slack/165)

### CODE REVIEW

**Comment by dlsniper** [comment]
Thanks for the PR! Unfortunately it's not mergeable anymore due to a previous PR (I suspect it was yours to fix another error). Would you mind fixing the issues here so that this can be merged again?
Also please add a bit of documentation on how the user is expected to set the ` Reader ` field instead of the ` File ` field.
Thank you !

**Comment by dlsniper** [comment]
As a small heads-up, I'll push shortly an update to allow setting of context for the API which should allow full usage of the https://godoc.org/cloud.google.com/go/trace#HTTPClient and other clients.

**Comment by dennwc** [comment]
Done. Please take a look.

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/nlopes/slack/165#-:-KlErxKUwkr1HrJkbzxo:b-29aia4)*

**Comment by dlsniper** [comment]
LGTM, thank you for the quick reply.

**Pull request merged**
