### PR TITLE
Seems the token was missing from the request.

### PR DESCRIPTION
**Pull request by aubelsb2**
As far as I can tell it's because of a token is missing.

### CODE REVIEW

**Comment by aubelsb2** [comment]
Probably handled in the http client.

**Comment by aubelsb2** [comment]
Verified to fix my issue. Seems they are checking for unnecessary parameters or at least token being in the wrong location.

**Comment by kanata2** [comment]
@aubelsb2

I commented related issue. https://github.com/slack-go/slack/issues/903#issuecomment-800505141
Could you fix other codes where same problems occur too?(if exists)
If it is difficult, please let me know so I can find the time to do it.

**Comment by bailantaotao** [comment]
Is there any update for this?

**Comment by aubelsb2** [comment]
When I get a weekend spare I can work on it.

**Comment by raylas** [comment]
Would also love to see this merged ☝🏼

**Comment by joshm91** [comment]
Looks like #921 fixes this issue properly. This library is pretty much broken to any newcomers at the moment so it'd be great to get the fix merged ASAP. Thanks!

**Review by kanata2 — APPROVED** [review]

**Comment by kanata2** [comment]
Relased in v0.8.3

**Comment by arran4** [comment]
Following up from personal account. Does effort still need to be done by me? I feel like the change to remove query param token from the library will require significant change.

**Comment by kanata2** [comment]
In my recognition, #857 was resolved in v0.8.3.

However it may be better to use application/json as Slack's recommendation(the followings).

> Some methods, like chat.postMessage and dialog.open feature arguments that accept an associative JSON array. These methods can be difficult to properly construct when using a application/x-www-form-urlencoded Content-type, and we strongly recommend using JSON-encoded bodies instead.

**Pull request merged**
