### PR TITLE
renamed channel arg to either channelId or channelName

### LINKED ISSUE #202: Consistency - channel argument is in some cases channel name, in others channel id
```
rtm := slack.New(token).NewRTM()
...
rtm.JoinChannel(channel string) // expects channel name
rtm.LeaveChannel(channel string) // expects channel id
rtm.GetChannelInfo(channel string) // expects channel id
```
would be good to make this consistent (change join channel to accept channel id instead of name) and also rename arguments so it is clear if it is channel name or id: `LeaveChannel(channelId string)`

### PR DESCRIPTION
**Pull request by pete911**
this closes #202 I have only renamed fields that will not break anyones code

### CODE REVIEW

**Comment by dvdplm** [comment]
I think this is a good change, but it should be `channelID` not `channelId` (as per Go's formatting standard).

**Comment by pete911** [comment]
@dvdplm updated (sorry didn't notice `ID` is used instead of `Id` everywhere else in the code)

**Comment by mkungla** [comment]
@pete911 perhaps squash your commits

**Comment by pete911** [comment]
@mkungla don't want to sound rude, but the last commit (and pull request) has been merged on 25th of July, this pull request has been here for 22 days ... So I feel like we should first address #207

**Comment by mkungla** [comment]
@pete911 I do agree with that

**Comment by james-lawrence** [comment]
Looks good, merging. Thanks @pete911 =)

**Pull request merged**
