### PR TITLE
 Go modules support

### PR DESCRIPTION
**Pull request by vcastellm**
Use go modules as vendoring method.

Still maintain the vendor folder to support older go versions.

Also PR to lusis/slack-test to support go modules and refactor to use latest nlopes/slack changes. 

Before merging this, the module replacement should be changed when this https://github.com/lusis/slack-test/pull/5 is merged.

### CODE REVIEW

**Comment by victorcoder** [comment]
Please relaunch build as it failed in travis side:
`The command "curl -L https://git.io/vp6lP | sh" failed and exited with 7 during .`

**Comment by james-lawrence** [comment]
+1 ping me when slack-test gets merged.

**Comment by james-lawrence** [comment]
@victorcoder I've pulled in slack-test as a package for this library. once #500 is merged a rebase and cleanup should let me merge this.

**Comment by vcastellm** [comment]
Thanks @james-lawrence I'll do it

**Comment by vcastellm** [comment]
@james-lawrence now it complains about a broken test

```
--- FAIL: TestServerSendMessageToChannel (2.00s)
	assertions.go:256: 
			Error Trace:	server_test.go:32
			Error:      	Should be true
```

**Comment by james-lawrence** [comment]
I'm aware its in the testing package, its on my list to fix probably tomorrow not a blocker for you. (I merged it in knowing it was broken to unlock some other work)

**Comment by vcastellm** [comment]
Thanks, let me know to rebase and build

**Comment by james-lawrence** [comment]
I'll likely just merge this in as in you're fine =)

**Pull request merged**
