### PR TITLE
Add bot_message subtype to MessageEvent

### PR DESCRIPTION
**Pull request by whithajess**
This adds https://api.slack.com/events/message/bot_message which is supported via the events api.

It seems like this is already added in `messages.go` but only the most basic message is defined in the MessageEvent could just use that if preferred the only thing it seems to be missing is ChannelType.

There is a bunch of other support messages in events:
- https://api.slack.com/events/message/thread_broadcast
- https://api.slack.com/events/message/reply_broadcast
- https://api.slack.com/events/message/message_replied
- https://api.slack.com/events/message/message_deleted
- https://api.slack.com/events/message/message_changed
- https://api.slack.com/events/message/me_message

I am happy to implement them all in this style or alternatively into `messages.go` where missing.

Thanks for your work on this project please let me know if you need me to make any changes 😄

### CODE REVIEW

**Comment by whithajess** [comment]
Need this to be able to work out that a bot is sending the message and not to reply to itself 😄

**Review by ruudk — APPROVED** [review]
Sweet!!! I was just looking for this 🙌

**Comment by james-lawrence** [comment]
LGTM, resolve conflicts an I'll merge.

**Comment by whithajess** [comment]
Resolved conflicts - looks a little messy in the file change but all fields are still there (moved from the basic messaged event) and aligned correctly. @james-lawrence

**Comment by whithajess** [comment]
Easier to see if you view the whole file.

**Pull request merged**
