### PR TITLE
channels list pagination

### LINKED ISSUE #522: GetChannels does not support pagination
If Slack team has more than 1k channels, there's no way to get the complete list of channels.

### PR DESCRIPTION
**Pull request by podtserkovskiy**
Hi!
This PR fixes #522.
I've made it like the get users method 😃

### CODE REVIEW

**Comment by jamiehannaford** [comment]
Hey @james-lawrence @alyosha, would it be possible to give this PR a quick 👀 ?

**Comment by jamiehannaford** [comment]
Hey @ollieparsley, would it be possible to give this PR a quick 👀 ?

**Comment by ollieparsley** [comment]
Hey @podtserkovskiy and @jamiehannaford. I'm not familiar with this part of the code yet. But since no method signatures are changing and it's not a major change, I'll merge.

**Comment by jamiehannaford** [comment]
Thank you!

**Pull request merged**
