### PR TITLE
Update error handling for gorilla/websocket ReadJSON()

### PR DESCRIPTION
**Pull request by parsley42**
Even after the previous fixes for #260 and #264, I had problems with a robot panic'ing in gorilla/websocket after a few days. I did some digging around in the gorilla/websocket code. The 'ReadJSON' function called from receiveIncomingEvent() returns one of three possible error values:
 1. io.ErrUnexpectedEOF (but never io.EOF) from json ... Decode()
 2. The error value from NextReader(...)
 3. Other error values from json ... Decode()

From the comments for NextReader():
```go
// Applications must break out of the application's read loop when this method
// returns a non-nil error value. Errors returned from this method are
// permanent. Once this method returns a non-nil error, all subsequent calls to
// this method return the same error.
```

For the first case, I'm forcing a ping. For the second and third case, it wasn't clear to me that the call to websocket.IsCloseError(...) catches all possible error returns from NextReader(), and I don't know a straightforward means of differentiating all json Decode() error values from all NextReader() error values. I would guess that non-`io.ErrUnexpectedEOF` error values from json Decode() are unlikely, and more likely I was getting error values returned from NextReader() that weren't being handled. Given the comments on NextReader(), I felt the safest way to handle other errors was to kill the connection to force reconnect.

I'm currently running with this patch for [Gopherbot](https://github.com/lnxjedi/gopherbot), but would appreciate others having a look and testing. @jdanlewis - what are your thoughts?

### CODE REVIEW

**Comment by jdanlewis** [comment]
@parsley42 I ran a couple of short tests and this seems to be fine, but I'm not able to force an error besides the websocket.CloseError. 

If you want to distinguish between errors from JSON Decode and NextReader, we could decode the JSON ourselves. Then, we could force reconnect anytime NextReader returns an error.

**Comment by james-lawrence** [comment]
LGTM. sorry for the delay.

**Comment by ArcticSnowman** [comment]
@james-lawrence  When can we expect a release with this in?

**Comment by james-lawrence** [comment]
0.4.0 should have it?

**Comment by ArcticSnowman** [comment]
Ah that's not been made a release...  so the latest is still 0.2.0.... afaik
Managed to get govendor to update the package..

**Comment by james-lawrence** [comment]
ah, I consider tags as the release. sorry will make a note to ensure github has the releases as well.

**Pull request merged**
