### PR TITLE
make NewRTM configurable

### PR DESCRIPTION
**Pull request by james-lawrence**
- adds dialer for managed RTM.
- deprecates the RTMWithOptions method.

### CODE REVIEW

**Comment by james-lawrence** [comment]
failure isn't understood, I suspect a timeout default causing it to hang.

**Comment by zellyn** [comment]
Oh interesting. I missed this while creating #263. I think the switch to `RTMOption` is fine, but I'd argue that a `websocket.Dialer` is a better choice than a `net.Dialer` for changing how connections happen, because it has more websocket-specific stuff in it, in addition to a `net.Dialer` equivalent.

**Comment by zellyn** [comment]
Of course, this leaks the gorilla `websocket.Dialer` type from the `nlopes/slack` package. I suppose once we move a few Go releases into the future, we could create an Alias.

**Comment by james-lawrence** [comment]
@zellyn likely this PR won't be merged until I (or someone else!) gets a chance to look into the test failures.

I won't have time for the next few months probably due to other projects, work, and personal time. =/

**Comment by zellyn** [comment]
@james-lawrence I'll incorporate these option-param changes into #263 and update it… any suggestions on other maintainers to ping?

**Comment by james-lawrence** [comment]
I'll be able to review, just not investigate, but any one of the other maintainers can review as well.

**Comment by zellyn** [comment]
@james-lawrence #269 is a combination of your PR and my old one, #263. The reason the tests were failing is that defaulting `UseStart` to `false` was hanging indefinitely. [Here's the fix](https://github.com/nlopes/slack/pull/269/files#diff-b10174736060c94b907283ae65ad8d80R24). I haven't figured out why yet, although I suspect it might be the test fake. ¯\\\_(ツ)\_/¯

**Pull request closed without merging**
