### PR TITLE
chore: enable to upload file without channel param

### PR DESCRIPTION
**Pull request by nakamasato**
##### Pull Request Guidelines

These are recommendations for pull requests.
They are strictly guidelines to help manage expectations.

##### PR preparation
Run `make pr-prep` from the root of the repository to run formatting, linting and tests.

##### Should this be an issue instead
- [ ] is it a convenience method? (no new functionality, streamlines some use case)
- [ ] exposes a previously private type, const, method, etc.
- [ ] is it application specific (caching, retry logic, rate limiting, etc)
- [ ] is it performance related.

##### API changes

Since API changes have to be maintained they undergo a more detailed review and are more likely to require changes.

- no tests, if you're adding to the API include at least a single test of the happy case.
- If you can accomplish your goal without changing the API, then do so.
- dependency changes. updates are okay. adding/removing need justification.

###### Examples of API changes that do not meet guidelines:
- in library cache for users. caches are use case specific.
- Convenience methods for Sending Messages, update, post, ephemeral, etc. consider opening an issue instead.

###### Ref
- https://api.slack.com/methods/files.completeUploadExternal

### CODE REVIEW

**Comment by 0xdeafcafe** [comment]
Anything I can do to help push this through? Would be really useful for us.

**Comment by nakamasato** [comment]
@0xdeafcafe Thanks!I wanted to upload a file without sending out to the channel but after roughly checking the API, i'm not very sure if it's possible from the api perspective and kept my pr draft. I saw you already made your own PR. Let's see there!

**Comment by 0xdeafcafe** [comment]
> @0xdeafcafe Thanks!I wanted to upload a file without sending out to the channel but after roughly checking the API, i'm not very sure if it's possible from the api perspective and kept my pr draft. I saw you already made your own PR. Let's see there!

We're using a fork of the repo with my PR on production at the moment, so I can confirm it works thankfully.

**Comment by lorenzoaiello** [comment]
Thanks for helping get the ball started @nakamasato - I'm closing this in favor of #1293

**Pull request closed without merging**
