### PR TITLE
Feature/slack buttons

### PR DESCRIPTION
**Pull request by basheuft**
This PR adds code for constructing message attachments with interactive buttons.

### CODE REVIEW

**Comment by dlsniper** [comment]
@nlopes if @101Bas rebases the PR can we get this merged please? I'd like to be able to use this for the Slack bot for gophers: https://github.com/gopheracademy/gopher and I'd rather not use my own fork. What do you think?

**Comment by dlsniper** [comment]
Optionally I can do the rebase in a separate branch so that @101Bas still gets the credit for the changes.

**Comment by dlsniper** [comment]
Actually nvm, I just upgraded and this is there, this can be closed, sorry for noise. Thank you for the work on this.

**Comment by nlopes** [comment]
Sorry, this had been merged previously. Apologies for the late reply.

**Pull request closed without merging**
