### PR TITLE
Fixing set-deadline

### PR DESCRIPTION
**Pull request by fclaude**

### CODE REVIEW

**Review by tobert — APPROVED** [review]

**Review by tobert — COMMENTED** [review]
I spoke too soon. Previous versions of this patch started disconnecting within a few seconds of startup. I'm running with this patch on my test bot now and it's disconnecting about every 10 seconds regardless of connection health.

2016/09/28 09:35:01 unexpected message: {Type:incoming_error Data:write tcp x.x.x.x:52966->54.208.183.10:443: i/o timeout}
2016/09/28 09:35:12 unexpected message: {Type:disconnected Data:0xc42093a63a}
2016/09/28 09:35:12 unexpected message: {Type:connecting Data:0xc42093a680}
2016/09/28 09:35:12 unexpected message: {Type:incoming_error Data:read tcp x.x.x.x:52966->54.208.183.10:443: use of closed network connection}
2016/09/28 09:35:13 ConnectedEvent - retreived bot ID "Uxxxxxxxx"
2016/09/28 09:35:13 HelloEvent

**Comment by fclaude** [comment]
Yeah, actually, it has a problem by leaving it outside the if (because conn could be nil and the library crashes). But inside it has a different problem, the deadline is fixed, and should be updated every time. It might be better to remove it or reposition it.

**Comment by fclaude** [comment]
I'll send you a proposal in a few minutes.

**Comment by fclaude** [comment]
Uploaded new version @tobert . What script were you using for that test so as to try it myself too?

**Comment by tobert** [comment]
@fclaude I'll test again in the morning. All I did was patch my vendored copy and run my test bot for a few minutes.  The issues show up quickly in my experience.

**Comment by lupine** [comment]
Any chance of getting this merged? I just came across this problem and was about to open a PR myself! :)

**Comment by nlopes** [comment]
I haven't had time to test this myself, so I am erring on the side of caution. Potentially this weekend I'll get to it.

**Comment by tobert** [comment]
I have a build against @fclaude's fork running over night for testing.

**Comment by tobert** [comment]
My test bot with this code is running fine this morning. LGTM

**Comment by nlopes** [comment]
Thank you @fclaude !

**Pull request merged**
