### PR TITLE
Added a timestamp string argument to the rtm.NewOutgoingMessage function

### PR DESCRIPTION
**Pull request by tylarb**
Enables function to be used to reply to or start a new thread

Per slack guidelines, an empty string starts a new thread/posts directly to channel, but any TS string that matches a previous post adds a reply. Test fix just passes an empty string.

### CODE REVIEW

**Comment by james-lawrence** [comment]
break API compat, i'd recommend some option style varg instead.

**Comment by tylarb** [comment]
Updated the commit to use a structure similar to that in chat.go. 

I also added a "ThreadBroadcast" bool to the outgoing message struct - according to [SlackAPI](https://api.slack.com/docs/message-threading), "ThreadBroadcast" the title of the feature, but it actually looks like "reply_broadcast" is the json bool which is handled correctly when posting - the docs don't give a relevant example, but see the [python API for reference](https://github.com/slackapi/python-slackclient/blob/8a6e36e55e56a3e41154b824a883fd16a272dc8f/slackclient/client.py#L138)

I tested both of these features, and the syntax should be sufficient to extend in the future, although I don't know how much it will be required to as the RTM API will seem to be somewhat feature limited compared to the Events API, etc.

**Comment by tylarb** [comment]
I also think this thread + thread broadcast could be included as an option in the chat API but this PR currently resolves my immediate need as I'm only using RTM for now. 

Do you want any change/addition to the chat as well, or is that OK to be in a separate PR?

**Comment by james-lawrence** [comment]
Would love the addition to the chat api. will take it however you wish to provide it =)

**Comment by ghostsquad** [comment]
Resolves #280

**Pull request merged**
