### PR TITLE
Sends an invitation to a Slack Connect channel

### PR DESCRIPTION
**Pull request by nopcoder**
Support [https://api.slack.com/methods/conversations.inviteShared](https://api.slack.com/methods/conversations.inviteShared)

### CODE REVIEW

**Review by parsley42 — APPROVED** [review]
I'm filling in for a bit on maintenance. Thanks for writing the tests. I don't see anything scary here that might break, approved.

**Comment by parsley42** [comment]
@nopcoder I think you'll need to close and re-open this PR for the checks to run.

**Comment by parsley42** [comment]
Closing and reopening for checks.

**Comment by nopcoder** [comment]
Thanks!

**Pull request merged**
